# Generated by Django 6.0.3 on 2026-03-04 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.CharField(max_length=200)),
                ('heure', models.CharField(max_length=10)),
                ('couverts', models.PositiveSmallIntegerField(default=2)),
                ('canal', models.CharField(max_length=50)),
                ('statut', models.CharField(max_length=50)),
                ('statut_type', models.CharField(default='pending', max_length=20)),
            ],
            options={
                'ordering': ['heure'],
            },
        ),
        migrations.CreateModel(
            name='SupplierOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produit', models.CharField(max_length=200)),
                ('fournisseur', models.CharField(max_length=200)),
                ('prix', models.CharField(max_length=50)),
                ('variation', models.CharField(default='0%', max_length=20)),
                ('variation_type', models.CharField(default='neutral', max_length=20)),
                ('stock', models.CharField(max_length=50)),
                ('stock_type', models.CharField(default='medium', max_length=20)),
                ('derniere_cmd', models.CharField(blank=True, max_length=20)),
            ],
            options={
                'ordering': ['produit'],
            },
        ),
        migrations.CreateModel(
            name='TeamShift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(max_length=10)),
                ('role', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('status', models.CharField(default='unassigned', max_length=20)),
            ],
            options={
                'ordering': ['time', 'role'],
            },
        ),
    ]
