# Generated by Django 6.0.3 on 2026-03-14 13:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_erd_schema'),
    ]

    operations = [
        migrations.AddField(
            model_name='formule',
            name='menus',
            field=models.ManyToManyField(blank=True, related_name='formules', through='api.Appartenance_Formule_Menu', to='api.menu'),
        ),
        migrations.AddField(
            model_name='menu',
            name='groupes',
            field=models.ManyToManyField(blank=True, related_name='menus', through='api.Appartenance_Groupe_Menu', to='api.groupe_menu'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='tables',
            field=models.ManyToManyField(blank=True, related_name='reservations', through='api.Detail_Reservation_Table', to='api.table'),
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('role', models.CharField(max_length=100)),
                ('initiales', models.CharField(blank=True, max_length=10)),
                ('heures_semaine', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('color', models.CharField(default='#e3f2fd', max_length=20)),
                ('salle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='api.salle')),
            ],
            options={
                'ordering': ['nom'],
            },
        ),
        migrations.CreateModel(
            name='PlanningShift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('type_shift', models.CharField(choices=[('Midi', 'Midi'), ('Soir', 'Soir'), ('Journée', 'Journée')], default='Midi', max_length=20)),
                ('heure_debut', models.CharField(max_length=10)),
                ('heure_fin', models.CharField(max_length=10)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to='api.employee')),
            ],
            options={
                'ordering': ['date', 'heure_debut'],
                'unique_together': {('employee', 'date', 'type_shift')},
            },
        ),
    ]
