# Generated by Django 6.0.3 on 2026-03-14 14:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_planning_employee_shift'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanningCapacity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.PositiveSmallIntegerField()),
                ('type_shift', models.CharField(choices=[('Midi', 'Midi'), ('Soir', 'Soir')], max_length=20)),
                ('required_count', models.PositiveSmallIntegerField(default=0)),
                ('salle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planning_capacities', to='api.salle')),
            ],
            options={
                'ordering': ['salle', 'day_of_week', 'type_shift'],
                'unique_together': {('salle', 'day_of_week', 'type_shift')},
            },
        ),
    ]
