# Generated by Django 6.0.3 on 2026-03-14 14:58

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_stock_movement'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_ingredient', models.CharField(max_length=200)),
                ('unite', models.CharField(default='kg', help_text='kg, L, pièce, etc.', max_length=50)),
                ('stock_actuel', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=12)),
                ('seuil_alerte', models.DecimalField(blank=True, decimal_places=3, help_text='Alert when stock_actuel falls below this', max_digits=12, null=True)),
                ('salle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='api.salle')),
            ],
            options={
                'ordering': ['nom_ingredient'],
                'unique_together': {('salle', 'nom_ingredient')},
            },
        ),
        migrations.CreateModel(
            name='IngredientMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_delta', models.DecimalField(decimal_places=3, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.CharField(blank=True, max_length=500)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='api.ingredient')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ingredient_movements', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
