# Generated by Django 6.0.3 on 2026-03-14 16:26

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_commandes_fournisseur'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appartenance_menu_plat',
            name='menu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lien_plats', to='api.menu'),
        ),
        migrations.AlterField(
            model_name='appartenance_menu_plat',
            name='plat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lien_menus', to='api.plat'),
        ),
        migrations.CreateModel(
            name='Composition_Plat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.DecimalField(decimal_places=4, default=Decimal('0'), help_text='Quantité par portion / unité de vente du plat', max_digits=12)),
                ('unite', models.CharField(blank=True, help_text="Unité (vide = celle de l'ingrédient)", max_length=50)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compositions_plat', to='api.ingredient')),
                ('plat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compositions', to='api.plat')),
            ],
            options={
                'ordering': ['plat', 'ingredient'],
                'unique_together': {('plat', 'ingredient')},
            },
        ),
    ]
