# Generated by Django 6.0.3 on 2026-03-14 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_composition_plat_et_menu_plats'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Composition_Plat',
        ),
    ]
