# Generated by Django 6.0.3 on 2026-03-14 16:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_remove_composition_plat'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='canal',
            field=models.CharField(blank=True, choices=[('site', 'Site'), ('telephone', 'Téléphone'), ('thefork', 'TheFork'), ('autre', 'Autre')], max_length=30),
        ),
        migrations.AlterField(
            model_name='detail_reservation_table',
            name='reservation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lien_tables', to='api.reservation'),
        ),
        migrations.AlterField(
            model_name='detail_reservation_table',
            name='table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lien_reservations', to='api.table'),
        ),
    ]
