# Generated by Django 5.1.7 on 2025-08-18 22:20

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
                ('unite', models.CharField(max_length=50)),
                ('prix_unitaire', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'verbose_name': 'T_HOLLY_PI_INGREDIENTS',
                'verbose_name_plural': 'T_HOLLY_PI_INGREDIENTS',
                'db_table': 'T_HOLLY_PI_INGREDIENTS',
            },
        ),
        migrations.CreateModel(
            name='Reapprovisionnement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite_ajoutee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('prix_achat', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.ingredient')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.restaurant')),
            ],
            options={
                'verbose_name': 'T_HOLLY_PI_REAPPROVISIONNEMENTS',
                'verbose_name_plural': 'T_HOLLY_PI_REAPPROVISIONNEMENTS',
                'db_table': 'T_HOLLY_PI_REAPPROVISIONNEMENTS',
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite_en_stock', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('seuil_alerte', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('cout_moyen_pondere', models.DecimalField(decimal_places=4, default=Decimal('0'), help_text="Coût moyen pondéré de l'ingrédient en stock", max_digits=10)),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.ingredient')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.restaurant')),
            ],
            options={
                'verbose_name': 'T_HOLLY_PI_STOCKS',
                'verbose_name_plural': 'T_HOLLY_PI_STOCKS',
                'db_table': 'T_HOLLY_PI_STOCKS',
                'indexes': [models.Index(fields=['restaurant', 'ingredient'], name='T_HOLLY_PI__restaur_854932_idx'), models.Index(fields=['restaurant', 'quantite_en_stock', 'seuil_alerte'], name='T_HOLLY_PI__restaur_87854d_idx'), models.Index(fields=['ingredient', 'cout_moyen_pondere'], name='T_HOLLY_PI__ingredi_04a780_idx'), models.Index(fields=['restaurant', 'ingredient', 'quantite_en_stock'], name='T_HOLLY_PI__restaur_e2ba5d_idx')],
                'unique_together': {('restaurant', 'ingredient')},
            },
        ),
    ]
