# Generated by Django 5.1.7 on 2025-12-08 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="ingredient",
            options={
                "ordering": ["nom"],
                "verbose_name": "T_HOLLY_PI_INGREDIENTS",
                "verbose_name_plural": "T_HOLLY_PI_INGREDIENTS",
            },
        ),
        migrations.AlterModelOptions(
            name="reapprovisionnement",
            options={
                "ordering": ["-date_ajout"],
                "verbose_name": "T_HOLLY_PI_REAPPROVISIONNEMENTS",
                "verbose_name_plural": "T_HOLLY_PI_REAPPROVISIONNEMENTS",
            },
        ),
        migrations.AlterModelOptions(
            name="stock",
            options={
                "ordering": ["ingredient__nom"],
                "verbose_name": "T_HOLLY_PI_STOCKS",
                "verbose_name_plural": "T_HOLLY_PI_STOCKS",
            },
        ),
    ]
