# Generated by Django 5.1.7 on 2025-08-18 22:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('salles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nom_client', models.CharField(max_length=100)),
                ('nombre_personnes', models.PositiveIntegerField()),
                ('date_heure', models.DateTimeField()),
                ('telephone', models.CharField(max_length=20)),
                ('salle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='salles.salle')),
            ],
            options={
                'verbose_name': 'T_HOLLY_PI_RESERVATIONS',
                'verbose_name_plural': 'T_HOLLY_PI_RESERVATIONS',
                'db_table': 'T_HOLLY_PI_RESERVATIONS',
            },
        ),
    ]
