# Generated by Django 5.1.7 on 2025-12-08 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reservations", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="reservation",
            options={
                "ordering": ["date_heure"],
                "verbose_name": "T_HOLLY_PI_RESERVATIONS",
                "verbose_name_plural": "T_HOLLY_PI_RESERVATIONS",
            },
        ),
    ]
