# Generated by Django 5.1.7 on 2026-03-05 21:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reservations", "0002_alter_reservation_options"),
        ("salles", "0002_alter_salle_options_alter_table_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="reservation",
            name="table",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reservations",
                to="salles.table",
            ),
        ),
    ]
