# Generated by Django 5.1.7 on 2025-08-18 22:20

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('menu', '0001_initial'),
        ('restaurant', '0001_initial'),
        ('salles', '0001_initial'),
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commande',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nb_articles', models.IntegerField(db_index=True, default=0)),
                ('montant', models.DecimalField(db_index=True, decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('statut', models.CharField(choices=[('EN_COURS', 'En cours'), ('VALIDEE', 'Validée'), ('ANNULEE', 'Annulée')], db_index=True, default='EN_COURS', max_length=20)),
                ('cout_total_marchandises_vendues', models.DecimalField(blank=True, decimal_places=2, help_text='CMV total pour cette commande', max_digits=10, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.employe')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.restaurant')),
                ('table', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='salles.table')),
            ],
            options={
                'verbose_name': 'T_HOLLY_PI_COMMANDES',
                'verbose_name_plural': 'T_HOLLY_PI_COMMANDES',
                'db_table': 'T_HOLLY_PI_COMMANDES',
            },
        ),
        migrations.CreateModel(
            name='CommandeHistoric',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nb_articles', models.IntegerField(db_index=True, default=0)),
                ('montant', models.DecimalField(db_index=True, decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('created_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('statut', models.CharField(choices=[('EN_COURS', 'En cours'), ('VALIDEE', 'Validée'), ('ANNULEE', 'Annulée')], db_index=True, max_length=20)),
                ('cout_total_marchandises_vendues', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('archived_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='staff.employe')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='restaurant.restaurant')),
                ('table', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='salles.table')),
            ],
            options={
                'verbose_name': 'T_HOLLY_PI_COMMANDES_HISTORIC',
                'verbose_name_plural': 'T_HOLLY_PI_COMMANDES_HISTORIC',
                'db_table': 'T_HOLLY_PI_COMMANDES_HISTORIC',
            },
        ),
        migrations.CreateModel(
            name='LigneCommande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.PositiveIntegerField(db_index=True, default=1)),
                ('prix_unitaire', models.DecimalField(db_index=True, decimal_places=2, max_digits=10)),
                ('cout_marchandise_vendue', models.DecimalField(blank=True, decimal_places=2, help_text='CMV pour cette ligne de commande', max_digits=10, null=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.article')),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='commandes.commande')),
            ],
            options={
                'verbose_name': 'T_HOLLY_PI_LIGNE_COMMANDE',
                'verbose_name_plural': 'T_HOLLY_PI_LIGNE_COMMANDE',
                'db_table': 'T_HOLLY_PI_LIGNE_COMMANDE',
            },
        ),
        migrations.CreateModel(
            name='LigneCommandeHistoric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.PositiveIntegerField(db_index=True, default=1)),
                ('prix_unitaire', models.DecimalField(db_index=True, decimal_places=2, max_digits=10)),
                ('cout_marchandise_vendue', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='menu.article')),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='commandes.commandehistoric')),
            ],
            options={
                'verbose_name': 'T_HOLLY_PI_LIGNE_COMMANDE_HISTORIC',
                'verbose_name_plural': 'T_HOLLY_PI_LIGNE_COMMANDE_HISTORIC',
                'db_table': 'T_HOLLY_PI_LIGNE_COMMANDE_HISTORIC',
            },
        ),
        migrations.AddIndex(
            model_name='commande',
            index=models.Index(fields=['restaurant', 'created_at'], name='T_HOLLY_PI__restaur_e93dc2_idx'),
        ),
        migrations.AddIndex(
            model_name='commande',
            index=models.Index(fields=['restaurant', 'statut'], name='T_HOLLY_PI__restaur_cdfeb2_idx'),
        ),
        migrations.AddIndex(
            model_name='commande',
            index=models.Index(fields=['created_by', 'created_at'], name='T_HOLLY_PI__created_c3839d_idx'),
        ),
        migrations.AddIndex(
            model_name='commande',
            index=models.Index(fields=['restaurant', 'statut', 'created_at'], name='T_HOLLY_PI__restaur_6a5e82_idx'),
        ),
        migrations.AddIndex(
            model_name='commande',
            index=models.Index(fields=['statut', 'created_at'], name='T_HOLLY_PI__statut_e7e3ad_idx'),
        ),
        migrations.AddIndex(
            model_name='commandehistoric',
            index=models.Index(fields=['restaurant', 'created_at'], name='T_HOLLY_PI__restaur_82ea6c_idx'),
        ),
        migrations.AddIndex(
            model_name='commandehistoric',
            index=models.Index(fields=['restaurant', 'statut'], name='T_HOLLY_PI__restaur_2b0c65_idx'),
        ),
        migrations.AddIndex(
            model_name='commandehistoric',
            index=models.Index(fields=['created_by', 'created_at'], name='T_HOLLY_PI__created_ea79cf_idx'),
        ),
        migrations.AddIndex(
            model_name='commandehistoric',
            index=models.Index(fields=['archived_at'], name='T_HOLLY_PI__archive_034457_idx'),
        ),
        migrations.AddIndex(
            model_name='lignecommande',
            index=models.Index(fields=['commande', 'article'], name='T_HOLLY_PI__command_83cb24_idx'),
        ),
        migrations.AddIndex(
            model_name='lignecommande',
            index=models.Index(fields=['article', 'prix_unitaire'], name='T_HOLLY_PI__article_d540bd_idx'),
        ),
        migrations.AddIndex(
            model_name='lignecommande',
            index=models.Index(fields=['commande', 'quantite'], name='T_HOLLY_PI__command_a52e3f_idx'),
        ),
        migrations.AddIndex(
            model_name='lignecommande',
            index=models.Index(fields=['article', 'quantite', 'prix_unitaire'], name='T_HOLLY_PI__article_673a93_idx'),
        ),
        migrations.AddIndex(
            model_name='lignecommande',
            index=models.Index(fields=['commande', 'cout_marchandise_vendue'], name='T_HOLLY_PI__command_a6ff8c_idx'),
        ),
        migrations.AddIndex(
            model_name='lignecommandehistoric',
            index=models.Index(fields=['commande', 'article'], name='T_HOLLY_PI__command_ebef0b_idx'),
        ),
        migrations.AddIndex(
            model_name='lignecommandehistoric',
            index=models.Index(fields=['article', 'prix_unitaire'], name='T_HOLLY_PI__article_df469a_idx'),
        ),
    ]
