# Generated by Django 5.1.7 on 2025-12-12 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("commandes", "0002_alter_commande_options"),
        ("restaurant", "0005_alter_restaurant_options"),
        ("salles", "0002_alter_salle_options_alter_table_options"),
        ("staff", "0005_alter_employe_options_alter_typeemploye_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="commande",
            name="priorite",
            field=models.CharField(
                choices=[
                    ("LOW", "Basse"),
                    ("NORMAL", "Normale"),
                    ("HIGH", "Haute"),
                    ("URGENT", "Urgente"),
                ],
                db_index=True,
                default="NORMAL",
                help_text="Priorité de la commande",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="commande",
            name="statut_cuisine",
            field=models.CharField(
                choices=[
                    ("PENDING", "En attente"),
                    ("IN_PROGRESS", "En préparation"),
                    ("READY", "Prête"),
                ],
                db_index=True,
                default="PENDING",
                help_text="Statut de la commande en cuisine",
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="commande",
            index=models.Index(
                fields=["restaurant", "statut_cuisine", "priorite"],
                name="T_HOLLY_PI__restaur_76043c_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="commande",
            index=models.Index(
                fields=["statut_cuisine", "priorite", "created_at"],
                name="T_HOLLY_PI__statut__8fde4f_idx",
            ),
        ),
    ]
