# Generated by Django 5.1.7 on 2026-03-02 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("commandes", "0003_commande_priorite_commande_statut_cuisine_and_more"),
        ("menu", "0002_alter_categoriearticle_nom_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="lignecommande",
            name="en_attente_service",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="Indique si la ligne est mise en attente (ex: dessert commandé à l'entrée).",
            ),
        ),
        migrations.AddIndex(
            model_name="lignecommande",
            index=models.Index(
                fields=["commande", "en_attente_service"],
                name="T_HOLLY_PI__command_2762b4_idx",
            ),
        ),
    ]
