# Generated by Django 5.1.7 on 2025-08-18 22:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('restaurant', '0001_initial'),
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Salle',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nom_salle', models.CharField(max_length=100)),
                ('capacite', models.PositiveIntegerField(default=0)),
                ('etage', models.IntegerField(default=0)),
                ('description', models.TextField(blank=True, null=True)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salles', to='restaurant.restaurant')),
            ],
            options={
                'verbose_name': 'T_HOLLY_PI_SALLES',
                'verbose_name_plural': 'T_HOLLY_PI_SALLES',
                'db_table': 'T_HOLLY_PI_SALLES',
                'unique_together': {('restaurant', 'nom_salle')},
            },
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('numero', models.PositiveIntegerField(default=1)),
                ('capacity', models.PositiveIntegerField(default=0)),
                ('reserved_seats', models.PositiveIntegerField(default=0)),
                ('is_occupied', models.BooleanField(default=False)),
                ('position_x', models.IntegerField(default=0, help_text='Position X de la table dans la salle')),
                ('position_y', models.IntegerField(default=0, help_text='Position Y de la table dans la salle')),
                ('employee_in_charge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.employe')),
                ('salle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tables', to='salles.salle')),
            ],
            options={
                'verbose_name': 'T_HOLLY_PI_TABLES',
                'verbose_name_plural': 'T_HOLLY_PI_TABLES',
                'db_table': 'T_HOLLY_PI_TABLES',
                'unique_together': {('salle', 'numero')},
            },
        ),
    ]
