# Generated by Django 5.1.7 on 2025-12-08 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("salles", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="salle",
            options={
                "ordering": ["id"],
                "verbose_name": "T_HOLLY_PI_SALLES",
                "verbose_name_plural": "T_HOLLY_PI_SALLES",
            },
        ),
        migrations.AlterModelOptions(
            name="table",
            options={
                "ordering": ["numero"],
                "verbose_name": "T_HOLLY_PI_TABLES",
                "verbose_name_plural": "T_HOLLY_PI_TABLES",
            },
        ),
    ]
