# Generated by Django 5.1.7 on 2025-08-18 22:20

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('restaurant', '0001_initial'),
        ('authentication', '0001_initial'),  # Dépendance explicite vers authentication
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeEmploye',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nom_type', models.CharField(max_length=50, unique=True, validators=[django.core.validators.RegexValidator('^[a-zA-Z\\s]+$', 'Le nom du type doit contenir uniquement des lettres et des espaces.')])),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'T_HOLLY_PI_TYPE_EMPLOYE',
                'verbose_name_plural': 'T_HOLLY_PI_TYPE_EMPLOYES',
                'db_table': 'T_HOLLY_PI_TYPE_EMPLOYES',
            },
        ),
        migrations.CreateModel(
            name='Employe',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator('^[a-zA-Z\\s-]+$', 'Le nom doit contenir uniquement des lettres, espaces ou tirets.')])),
                ('prenom', models.CharField(max_length=100, validators=[django.core.validators.RegexValidator('^[a-zA-Z\\s-]+$', 'Le prénom doit contenir uniquement des lettres, espaces ou tirets.')])),
                ('salaire', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('date_embauche', models.DateField(default=django.utils.timezone.now)),
                ('numero_telephone', models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator('^\\+?1?\\d{9,15}$', 'Le numéro de téléphone doit être valide.')])),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employe', to=settings.AUTH_USER_MODEL)),
                ('type_employe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employes', to='staff.typeemploye')),
            ],
            options={
                'verbose_name': 'T_HOLLY_PI_EMPLOYES',
                'verbose_name_plural': 'T_HOLLY_PI_EMPLOYES',
                'db_table': 'T_HOLLY_PI_EMPLOYES',
            },
        ),
        migrations.CreateModel(
            name='RestaurantEmploye',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('employe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='staff.employe')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.restaurant')),
            ],
            options={
                'verbose_name': 'T_HOLLY_PI_RESTAURANT_EMPLOYE',
                'verbose_name_plural': 'T_HOLLY_PI_RESTAURANT_EMPLOYE',
                'db_table': 'T_HOLLY_PI_RESTAURANT_EMPLOYE',
                'unique_together': {('restaurant', 'employe')},
            },
        ),
    ]
