# Generated by Django 5.1.7 on 2025-12-07 02:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_add_pin_code_to_employe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employe',
            name='pin_code',
            field=models.CharField(blank=True, help_text='Le PIN code est unique par restaurant (4 chiffres)', max_length=4, null=True, validators=[django.core.validators.RegexValidator('^\\d{4}$', 'Le PIN code doit contenir exactement 4 chiffres.')]),
        ),
    ]
