# Generated by Django 5.1.7 on 2025-12-07 02:45

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0004_alter_restaurant_code_naf'),
        ('staff', '0003_alter_employe_pin_code'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employe',
            options={'verbose_name': 'Employé', 'verbose_name_plural': 'Employés'},
        ),
        migrations.AlterModelOptions(
            name='restaurantemploye',
            options={'verbose_name': 'Association Restaurant-Employé', 'verbose_name_plural': 'Associations Restaurant-Employé'},
        ),
        migrations.AlterModelOptions(
            name='typeemploye',
            options={'verbose_name': "Type d'employé", 'verbose_name_plural': "Types d'employés"},
        ),
        migrations.AlterField(
            model_name='employe',
            name='nom',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator('^[a-zA-ZÀ-ÿ\\s-]+$', 'Le nom doit contenir uniquement des lettres, espaces ou tirets.')]),
        ),
        migrations.AlterField(
            model_name='employe',
            name='prenom',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator('^[a-zA-ZÀ-ÿ\\s-]+$', 'Le prénom doit contenir uniquement des lettres, espaces ou tirets.')]),
        ),
        migrations.AlterField(
            model_name='restaurantemploye',
            name='employe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restaurants_association', to='staff.employe'),
        ),
        migrations.AlterField(
            model_name='restaurantemploye',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employes_association', to='restaurant.restaurant'),
        ),
        migrations.AlterField(
            model_name='typeemploye',
            name='nom_type',
            field=models.CharField(max_length=50, unique=True, validators=[django.core.validators.RegexValidator('^[a-zA-ZÀ-ÿ\\s]+$', 'Le nom du type doit contenir uniquement des lettres et des espaces.')]),
        ),
    ]
