# Generated by Django 5.1.7 on 2025-12-08 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("staff", "0004_alter_employe_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="employe",
            options={
                "ordering": ["nom", "prenom"],
                "verbose_name": "Employé",
                "verbose_name_plural": "Employés",
            },
        ),
        migrations.AlterModelOptions(
            name="typeemploye",
            options={
                "ordering": ["nom_type"],
                "verbose_name": "Type d'employé",
                "verbose_name_plural": "Types d'employés",
            },
        ),
    ]
