# Generated by Django 5.1.7 on 2026-02-25 01:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0005_alter_employe_options_alter_typeemploye_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='restaurantemploye',
            options={'ordering': ['id'], 'verbose_name': 'Association Restaurant-Employé', 'verbose_name_plural': 'Associations Restaurant-Employé'},
        ),
        migrations.AlterField(
            model_name='employe',
            name='date_embauche',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
    ]
