# Generated by Django 5.1.7 on 2025-08-18 22:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('commandes', '0001_initial'),
        ('menu', '0001_initial'),
        ('restaurant', '0001_initial'),
        ('shared', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MethodePaiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(db_index=True, max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'T_HOLLY_PI_METHODES_PAIEMENT',
                'verbose_name_plural': 'T_HOLLY_PI_METHODES_PAIEMENT',
                'db_table': 'T_HOLLY_PI_METHODES_PAIEMENT',
            },
        ),
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(db_index=True, help_text='Numéro unique de la facture', max_length=255)),
                ('date', models.DateField(db_index=True, help_text="Date d'émission de la facture")),
                ('montant_ht', models.DecimalField(db_index=True, decimal_places=2, help_text='Montant hors taxes', max_digits=10)),
                ('montant_ttc', models.DecimalField(db_index=True, decimal_places=2, help_text='Montant toutes taxes comprises', max_digits=10)),
                ('montant_tva', models.DecimalField(db_index=True, decimal_places=2, help_text='Montant total de la TVA calculé', max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('etat', models.CharField(choices=[('en_attente', 'En attente'), ('payee', 'Payée'), ('annulee', 'Annulée')], db_index=True, max_length=255)),
                ('commande', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commandes.commande')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.restaurant')),
            ],
            options={
                'verbose_name': 'T_HOLLY_PI_FACTURES',
                'verbose_name_plural': 'T_HOLLY_PI_FACTURES',
                'db_table': 'T_HOLLY_PI_FACTURES',
            },
        ),
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(db_index=True, decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('facture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billing.facture')),
                ('methode_paiement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billing.methodepaiement')),
            ],
            options={
                'verbose_name': 'T_HOLLY_PI_PAIEMENTS',
                'verbose_name_plural': 'T_HOLLY_PI_PAIEMENTS',
                'db_table': 'T_HOLLY_PI_PAIEMENTS',
            },
        ),
        migrations.CreateModel(
            name='LigneFacture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.IntegerField(db_index=True)),
                ('prix_unitaire_ht', models.DecimalField(db_index=True, decimal_places=2, max_digits=10)),
                ('prix_unitaire_ttc', models.DecimalField(db_index=True, decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('facture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lignes', to='billing.facture')),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.article')),
                ('taux_tva', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shared.tauxtva')),
                ('paiement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billing.paiement')),
            ],
            options={
                'verbose_name': 'T_HOLLY_PI_LIGNES_FACTURE',
                'verbose_name_plural': 'T_HOLLY_PI_LIGNES_FACTURE',
                'db_table': 'T_HOLLY_PI_LIGNES_FACTURE',
            },
        ),
        migrations.AddIndex(
            model_name='facture',
            index=models.Index(fields=['restaurant', 'date'], name='T_HOLLY_PI__restaur_149aaf_idx'),
        ),
        migrations.AddIndex(
            model_name='facture',
            index=models.Index(fields=['restaurant', 'etat'], name='T_HOLLY_PI__restaur_98e50a_idx'),
        ),
        migrations.AddIndex(
            model_name='facture',
            index=models.Index(fields=['date', 'etat'], name='T_HOLLY_PI__date_9f322b_idx'),
        ),
        migrations.AddIndex(
            model_name='facture',
            index=models.Index(fields=['numero', 'restaurant'], name='T_HOLLY_PI__numero_e9f3c8_idx'),
        ),
        migrations.AddIndex(
            model_name='paiement',
            index=models.Index(fields=['facture', 'created_at'], name='T_HOLLY_PI__facture_49cdd5_idx'),
        ),
        migrations.AddIndex(
            model_name='paiement',
            index=models.Index(fields=['methode_paiement', 'created_at'], name='T_HOLLY_PI__methode_ef63e9_idx'),
        ),
        migrations.AddIndex(
            model_name='lignefacture',
            index=models.Index(fields=['facture', 'produit'], name='T_HOLLY_PI__facture_92b799_idx'),
        ),
        migrations.AddIndex(
            model_name='lignefacture',
            index=models.Index(fields=['produit', 'taux_tva'], name='T_HOLLY_PI__produit_32807d_idx'),
        ),
        migrations.AddIndex(
            model_name='lignefacture',
            index=models.Index(fields=['paiement', 'created_at'], name='T_HOLLY_PI__paiemen_0ecff7_idx'),
        ),
    ]
