# Generated by Django 5.1.7 on 2025-10-13 21:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
        ('commandes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='lignefacture',
            name='T_HOLLY_PI__paiemen_0ecff7_idx',
        ),
        migrations.RemoveField(
            model_name='lignefacture',
            name='paiement',
        ),
        migrations.AlterField(
            model_name='facture',
            name='commande',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='commandes.commandehistoric'),
        ),
    ]
