# Generated by Django 5.1.7 on 2025-12-08 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0002_remove_lignefacture_t_holly_pi__paiemen_0ecff7_idx_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="facture",
            options={
                "ordering": ["-date", "-created_at"],
                "verbose_name": "T_HOLLY_PI_FACTURES",
                "verbose_name_plural": "T_HOLLY_PI_FACTURES",
            },
        ),
        migrations.AlterModelOptions(
            name="lignefacture",
            options={
                "ordering": ["id"],
                "verbose_name": "T_HOLLY_PI_LIGNES_FACTURE",
                "verbose_name_plural": "T_HOLLY_PI_LIGNES_FACTURE",
            },
        ),
        migrations.AlterModelOptions(
            name="methodepaiement",
            options={
                "ordering": ["nom"],
                "verbose_name": "T_HOLLY_PI_METHODES_PAIEMENT",
                "verbose_name_plural": "T_HOLLY_PI_METHODES_PAIEMENT",
            },
        ),
        migrations.AlterModelOptions(
            name="paiement",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "T_HOLLY_PI_PAIEMENTS",
                "verbose_name_plural": "T_HOLLY_PI_PAIEMENTS",
            },
        ),
    ]
