# Generated by Django 5.1.7 on 2026-02-25 01:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_alter_facture_options_alter_lignefacture_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paiement',
            name='facture',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to='billing.facture'),
        ),
    ]
