# Generated by Django 5.1.7 on 2025-08-18 22:20

import apps.shared.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
        ('restaurant', '0001_initial'),
        ('shared', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategorieArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(db_index=True, help_text='Nom de la catégorie (ex: Entrée, Plat, Dessert, Boisson)', max_length=50, unique=True)),
                ('ordre_affichage', models.PositiveIntegerField(db_index=True, default=0, help_text="Ordre d'affichage de la catégorie dans le menu")),
                ('description', models.TextField(blank=True, help_text='Description optionnelle de la catégorie', null=True)),
                ('restaurant', models.ForeignKey(help_text='Restaurant associé à la catégorie', on_delete=django.db.models.deletion.CASCADE, to='restaurant.restaurant')),
            ],
            options={
                'verbose_name': 'T_HOLLY_PI_CATEGORIES_ARTICLE',
                'verbose_name_plural': 'T_HOLLY_PI_CATEGORIES_ARTICLE',
                'db_table': 'T_HOLLY_PI_CATEGORIES_ARTICLE',
                'ordering': ['ordre_affichage', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(db_index=True, help_text="Nom de l'article", max_length=100)),
                ('prix', models.DecimalField(db_index=True, decimal_places=2, help_text="Prix HT de l'article", max_digits=10)),
                ('description', models.TextField(blank=True, null=True)),
                ('disponible', models.BooleanField(db_index=True, default=True, help_text="Indique si l'article est disponible à la vente")),
                ('taux_tva', models.ForeignKey(default=apps.shared.models.TauxTVA.get_tva_par_defaut, help_text='Taux de TVA applicable par défaut pour cet article', on_delete=django.db.models.deletion.PROTECT, to='shared.tauxtva')),
                ('categorie', models.ForeignKey(help_text="Catégorie de l'article", on_delete=django.db.models.deletion.PROTECT, to='menu.categoriearticle')),
            ],
            options={
                'verbose_name': 'T_HOLLY_PI_ARTICLES',
                'verbose_name_plural': 'T_HOLLY_PI_ARTICLES',
                'db_table': 'T_HOLLY_PI_ARTICLES',
                'ordering': ['categorie__ordre_affichage', 'categorie__nom', 'nom'],
            },
        ),
        migrations.CreateModel(
            name='ArticleIngredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite_necessaire', models.DecimalField(db_index=True, decimal_places=2, max_digits=10)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='menu.article')),
                ('ingredient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.ingredient')),
            ],
            options={
                'verbose_name': 'T_HOLLY_PI_ARTICLE_INGREDIENT',
                'verbose_name_plural': 'T_HOLLY_PI_ARTICLE_INGREDIENT',
                'db_table': 'T_HOLLY_PI_ARTICLE_INGREDIENT',
                'indexes': [models.Index(fields=['article', 'ingredient'], name='T_HOLLY_PI__article_921b70_idx'), models.Index(fields=['ingredient', 'quantite_necessaire'], name='T_HOLLY_PI__ingredi_91e330_idx')],
                'unique_together': {('article', 'ingredient')},
            },
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['categorie', 'disponible'], name='T_HOLLY_PI__categor_2154a4_idx'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['disponible', 'prix'], name='T_HOLLY_PI__disponi_412ca3_idx'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['taux_tva', 'disponible'], name='T_HOLLY_PI__taux_tv_88064d_idx'),
        ),
        migrations.AddIndex(
            model_name='article',
            index=models.Index(fields=['nom', 'disponible'], name='T_HOLLY_PI__nom_061ee7_idx'),
        ),
    ]
