# Generated by Django 5.1.7 on 2025-08-18 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoriearticle',
            name='nom',
            field=models.CharField(db_index=True, help_text='Nom de la catégorie (ex: Entrée, Plat, Dessert, Boisson)', max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='categoriearticle',
            unique_together={('nom', 'restaurant')},
        ),
    ]
