# Generated by Django 5.1.7 on 2026-03-12 09:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("menu", "0002_alter_categoriearticle_nom_and_more"),
        ("restaurant", "0006_restaurant_latitude_restaurant_longitude"),
        ("shared", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="article",
            options={
                "ordering": [
                    "restaurant__nom_restaurant",
                    "categorie__ordre_affichage",
                    "categorie__nom",
                    "nom",
                ],
                "verbose_name": "T_HOLLY_PI_ARTICLES",
                "verbose_name_plural": "T_HOLLY_PI_ARTICLES",
            },
        ),
        migrations.RemoveIndex(
            model_name="article",
            name="T_HOLLY_PI__categor_2154a4_idx",
        ),
        migrations.RemoveIndex(
            model_name="article",
            name="T_HOLLY_PI__disponi_412ca3_idx",
        ),
        migrations.RemoveIndex(
            model_name="article",
            name="T_HOLLY_PI__taux_tv_88064d_idx",
        ),
        migrations.RemoveIndex(
            model_name="article",
            name="T_HOLLY_PI__nom_061ee7_idx",
        ),
        migrations.AlterUniqueTogether(
            name="categoriearticle",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="article",
            name="restaurant",
            field=models.ForeignKey(
                blank=True,
                help_text="Restaurant associé à l'article",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="restaurant.restaurant",
            ),
        ),
        migrations.AddIndex(
            model_name="article",
            index=models.Index(
                fields=["restaurant", "categorie", "disponible"],
                name="T_HOLLY_PI__restaur_1c8492_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="article",
            index=models.Index(
                fields=["restaurant", "disponible", "prix"],
                name="T_HOLLY_PI__restaur_6dfa03_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="article",
            index=models.Index(
                fields=["restaurant", "taux_tva", "disponible"],
                name="T_HOLLY_PI__restaur_c311dc_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="article",
            index=models.Index(
                fields=["restaurant", "nom", "disponible"],
                name="T_HOLLY_PI__restaur_ea5e0e_idx",
            ),
        ),
        migrations.RemoveField(
            model_name="categoriearticle",
            name="restaurant",
        ),
    ]
