# Generated by Django 5.1.7 on 2025-12-12 10:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("restaurant", "0005_alter_restaurant_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="Fournisseur",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("nom", models.CharField(db_index=True, max_length=200)),
                (
                    "contact_nom",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("telephone", models.CharField(blank=True, max_length=20, null=True)),
                ("adresse", models.TextField(blank=True, null=True)),
                ("ville", models.CharField(blank=True, max_length=100, null=True)),
                ("code_postal", models.CharField(blank=True, max_length=10, null=True)),
                (
                    "latitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                (
                    "longitude",
                    models.DecimalField(
                        blank=True, decimal_places=6, max_digits=9, null=True
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                ("actif", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Fournisseur",
                "verbose_name_plural": "Fournisseurs",
                "db_table": "T_HOLLY_PI_FOURNISSEURS",
                "ordering": ["nom"],
            },
        ),
        migrations.CreateModel(
            name="CommandeFournisseur",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "numero_commande",
                    models.CharField(db_index=True, max_length=50, unique=True),
                ),
                ("date_commande", models.DateField(db_index=True)),
                ("date_livraison_prevue", models.DateField(blank=True, null=True)),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Brouillon"),
                            ("SENT", "Envoyée"),
                            ("CONFIRMED", "Confirmée"),
                            ("DELIVERED", "Livrée"),
                            ("CANCELLED", "Annulée"),
                        ],
                        db_index=True,
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                (
                    "montant_total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "restaurant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="restaurant.restaurant",
                    ),
                ),
                (
                    "fournisseur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="commandes",
                        to="suppliers.fournisseur",
                    ),
                ),
            ],
            options={
                "verbose_name": "Commande fournisseur",
                "verbose_name_plural": "Commandes fournisseurs",
                "db_table": "T_HOLLY_PI_COMMANDES_FOURNISSEURS",
                "ordering": ["-date_commande"],
                "indexes": [
                    models.Index(
                        fields=["restaurant", "date_commande"],
                        name="T_HOLLY_PI__restaur_c7ce51_idx",
                    ),
                    models.Index(
                        fields=["fournisseur", "statut"],
                        name="T_HOLLY_PI__fournis_4e95d6_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="JourLivraison",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "jour",
                    models.CharField(
                        choices=[
                            ("MONDAY", "Lundi"),
                            ("TUESDAY", "Mardi"),
                            ("WEDNESDAY", "Mercredi"),
                            ("THURSDAY", "Jeudi"),
                            ("FRIDAY", "Vendredi"),
                            ("SATURDAY", "Samedi"),
                            ("SUNDAY", "Dimanche"),
                        ],
                        db_index=True,
                        max_length=10,
                    ),
                ),
                ("heure_livraison", models.TimeField(blank=True, null=True)),
                (
                    "fournisseur",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="jours_livraison",
                        to="suppliers.fournisseur",
                    ),
                ),
            ],
            options={
                "verbose_name": "Jour de livraison",
                "verbose_name_plural": "Jours de livraison",
                "db_table": "T_HOLLY_PI_JOURS_LIVRAISON",
                "ordering": ["jour"],
                "unique_together": {("fournisseur", "jour")},
            },
        ),
    ]
