import type { Reservation, RestaurantTable } from "./types"

export const RESTAURANT_TABLES: RestaurantTable[] = [
  { id: 1, number: 1, label: "T1", seats: 4 },
  { id: 2, number: 2, label: "T2", seats: 4 },
  { id: 3, number: 3, label: "T3", seats: 2 },
  { id: 4, number: 4, label: "T4", seats: 6 },
  { id: 5, number: 5, label: "T5", seats: 8 },
  { id: 6, number: 6, label: "T6", seats: 2 },
  { id: 7, number: 7, label: "T7", seats: 4 },
  { id: 8, number: 8, label: "T8", seats: 2 },
  { id: 9, number: 9, label: "T9", seats: 2 },
  { id: 10, number: 10, label: "T10", seats: 4 },
  { id: 11, number: 11, label: "T11", seats: 4 },
  { id: 12, number: 12, label: "Bar", seats: 6 },
]

function toLocalDateString(date: Date): string {
  const y = date.getFullYear()
  const m = String(date.getMonth() + 1).padStart(2, "0")
  const d = String(date.getDate()).padStart(2, "0")
  return `${y}-${m}-${d}`
}

const TODAY = toLocalDateString(new Date())

export const MOCK_RESERVATIONS: Reservation[] = [
  // ── Midi (8 résas) ──
  {
    id: "r1",
    clientName: "Martin Dupont",
    clientPhone: "06 12 34 56 78",
    clientEmail: "martin.dupont@email.fr",
    date: TODAY,
    time: "12:00",
    service: "midi",
    covers: 2,
    tableId: 3,
    tableNumber: 3,
    canal: "site",
    status: "arrivee",
    notes: "Anniversaire de mariage",
    allergies: [],
    dietTypes: [],
    pipeline: {
      currentStageId: "plat_servi",
      history: [
        { stageId: "installe", enteredAt: "2026-03-21T12:00:00" },
        { stageId: "commande_passee", enteredAt: "2026-03-21T12:08:00" },
        { stageId: "entree_servie", enteredAt: "2026-03-21T12:25:00" },
        { stageId: "plat_servi", enteredAt: "2026-03-21T12:45:00" },
      ],
    },
    estimatedDurationMinutes: 75,
    createdAt: new Date().toISOString(),
  },
  {
    id: "r2",
    clientName: "Sophie Laurent",
    clientPhone: "06 98 76 54 32",
    date: TODAY,
    time: "12:15",
    service: "midi",
    covers: 4,
    tableId: 1,
    tableNumber: 1,
    canal: "thefork",
    status: "confirmee",
    notes: "Allergie gluten",
    allergies: [],
    dietTypes: [],
    estimatedDurationMinutes: 75,
    createdAt: new Date().toISOString(),
  },
  {
    id: "r3",
    clientName: "Pierre Moreau",
    clientPhone: "06 11 22 33 44",
    date: TODAY,
    time: "12:30",
    service: "midi",
    covers: 6,
    tableId: 4,
    tableNumber: 4,
    canal: "telephone",
    status: "confirmee",
    notes: "Repas d'affaires — menu dégustation",
    allergies: [],
    dietTypes: [],
    estimatedDurationMinutes: 75,
    createdAt: new Date().toISOString(),
  },
  {
    id: "r4",
    clientName: "Claire Petit",
    clientPhone: "06 55 44 33 22",
    date: TODAY,
    time: "12:30",
    service: "midi",
    covers: 2,
    tableId: 6,
    tableNumber: 6,
    canal: "site",
    status: "en_attente",
    notes: "",
    allergies: [],
    dietTypes: [],
    estimatedDurationMinutes: 75,
    createdAt: new Date().toISOString(),
  },
  {
    id: "r5",
    clientName: "Jean-Marc Vidal",
    clientPhone: "06 77 88 99 00",
    clientEmail: "jm.vidal@pro.fr",
    date: TODAY,
    time: "13:00",
    service: "midi",
    covers: 3,
    tableId: 7,
    tableNumber: 7,
    canal: "telephone",
    status: "arrivee",
    notes: "Client VIP — habitué",
    allergies: [],
    dietTypes: [],
    pipeline: {
      currentStageId: "commande_passee",
      history: [
        { stageId: "installe", enteredAt: "2026-03-21T13:00:00" },
        { stageId: "commande_passee", enteredAt: "2026-03-21T13:10:00" },
      ],
    },
    estimatedDurationMinutes: 75,
    createdAt: new Date().toISOString(),
  },
  {
    id: "r6",
    clientName: "Isabelle Roux",
    clientPhone: "06 10 20 30 40",
    date: TODAY,
    time: "13:00",
    service: "midi",
    covers: 2,
    tableId: 9,
    tableNumber: 9,
    canal: "walk_in",
    status: "arrivee",
    notes: "",
    allergies: [],
    dietTypes: [],
    pipeline: {
      currentStageId: "installe",
      history: [{ stageId: "installe", enteredAt: "2026-03-21T13:02:00" }],
    },
    estimatedDurationMinutes: 75,
    createdAt: new Date().toISOString(),
  },
  {
    id: "r7",
    clientName: "François Garcia",
    clientPhone: "06 60 70 80 90",
    date: TODAY,
    time: "13:30",
    service: "midi",
    covers: 4,
    tableId: 2,
    tableNumber: 2,
    canal: "thefork",
    status: "annulee",
    notes: "Annulé la veille",
    allergies: [],
    dietTypes: [],
    createdAt: new Date().toISOString(),
  },
  {
    id: "r8",
    clientName: "Nathalie Bernard",
    clientPhone: "06 33 22 11 00",
    date: TODAY,
    time: "12:00",
    service: "midi",
    covers: 2,
    tableId: 8,
    tableNumber: 8,
    canal: "site",
    status: "no_show",
    notes: "",
    allergies: [],
    dietTypes: [],
    createdAt: new Date().toISOString(),
  },
  // ── Soir (7 résas) ──
  {
    id: "r9",
    clientName: "Antoine Leroy",
    clientPhone: "06 44 55 66 77",
    clientEmail: "a.leroy@mail.com",
    date: TODAY,
    time: "19:00",
    service: "soir",
    covers: 4,
    tableId: 2,
    tableNumber: 2,
    canal: "site",
    status: "confirmee",
    notes: "Demande terrasse si possible",
    allergies: [],
    dietTypes: [],
    estimatedDurationMinutes: 105,
    createdAt: new Date().toISOString(),
  },
  {
    id: "r10",
    clientName: "Marie Fontaine",
    clientPhone: "06 88 77 66 55",
    date: TODAY,
    time: "19:30",
    service: "soir",
    covers: 2,
    tableId: 3,
    tableNumber: 3,
    canal: "telephone",
    status: "confirmee",
    notes: "Végétarien × 2",
    allergies: [],
    dietTypes: [],
    estimatedDurationMinutes: 105,
    createdAt: new Date().toISOString(),
  },
  {
    id: "r11",
    clientName: "Olivier Mercier",
    clientPhone: "06 22 33 44 55",
    date: TODAY,
    time: "19:30",
    service: "soir",
    covers: 8,
    tableId: 5,
    tableNumber: 5,
    canal: "telephone",
    status: "en_attente",
    notes: "Grande tablée — anniversaire surprise",
    allergies: [],
    dietTypes: [],
    estimatedDurationMinutes: 105,
    createdAt: new Date().toISOString(),
  },
  {
    id: "r12",
    clientName: "Camille Durand",
    clientPhone: "06 99 88 77 66",
    date: TODAY,
    time: "20:00",
    service: "soir",
    covers: 2,
    tableId: 6,
    tableNumber: 6,
    canal: "thefork",
    status: "en_attente",
    notes: "",
    allergies: [],
    dietTypes: [],
    estimatedDurationMinutes: 105,
    createdAt: new Date().toISOString(),
  },
  {
    id: "r13",
    clientName: "Julien Thomas",
    clientPhone: "06 11 00 99 88",
    date: TODAY,
    time: "20:00",
    service: "soir",
    covers: 4,
    tableId: 10,
    tableNumber: 10,
    canal: "site",
    status: "annulee",
    notes: "Report au week-end prochain",
    allergies: [],
    dietTypes: [],
    createdAt: new Date().toISOString(),
  },
  {
    id: "r14",
    clientName: "Émilie Blanc",
    clientPhone: "06 55 66 77 88",
    clientEmail: "emilie.b@email.fr",
    date: TODAY,
    time: "20:30",
    service: "soir",
    covers: 6,
    tableId: 4,
    tableNumber: 4,
    canal: "walk_in",
    status: "confirmee",
    notes: "Menu dégustation accord mets-vins",
    allergies: [],
    dietTypes: [],
    estimatedDurationMinutes: 105,
    createdAt: new Date().toISOString(),
  },
  {
    id: "r15",
    clientName: "Lucas Girard",
    clientPhone: "06 00 11 22 33",
    date: TODAY,
    time: "21:00",
    service: "soir",
    covers: 2,
    tableId: 9,
    tableNumber: 9,
    canal: "thefork",
    status: "no_show",
    notes: "",
    allergies: [],
    dietTypes: [],
    createdAt: new Date().toISOString(),
  },
]
