import type {
  Employee,
  Shift,
  ServiceConfig,
  StaffingRequirement,
} from "./types"

export const employees: Employee[] = [
  {
    id: "emp-1",
    firstName: "Lucas",
    lastName: "Martin",
    role: "Chef de rang",
    department: "salle",
    contractHours: 35,
    avatarColor: "bg-blue-500",
  },
  {
    id: "emp-2",
    firstName: "Emma",
    lastName: "Dubois",
    role: "Serveuse",
    department: "salle",
    contractHours: 35,
    avatarColor: "bg-pink-500",
  },
  {
    id: "emp-3",
    firstName: "Hugo",
    lastName: "Bernard",
    role: "Chef cuisinier",
    department: "cuisine",
    contractHours: 39,
    avatarColor: "bg-orange-500",
  },
  {
    id: "emp-4",
    firstName: "Chloé",
    lastName: "Petit",
    role: "Commis",
    department: "cuisine",
    contractHours: 35,
    avatarColor: "bg-emerald-500",
  },
  {
    id: "emp-5",
    firstName: "Nathan",
    lastName: "Leroy",
    role: "Barman",
    department: "bar",
    contractHours: 35,
    avatarColor: "bg-purple-500",
  },
  {
    id: "emp-6",
    firstName: "Léa",
    lastName: "Moreau",
    role: "Serveuse",
    department: "salle",
    contractHours: 24,
    avatarColor: "bg-rose-500",
  },
  {
    id: "emp-7",
    firstName: "Thomas",
    lastName: "Simon",
    role: "Second de cuisine",
    department: "cuisine",
    contractHours: 39,
    avatarColor: "bg-amber-500",
  },
  {
    id: "emp-8",
    firstName: "Julie",
    lastName: "Laurent",
    role: "Plongeur",
    department: "plonge",
    contractHours: 35,
    avatarColor: "bg-teal-500",
  },
  {
    id: "emp-9",
    firstName: "Antoine",
    lastName: "Garcia",
    role: "Serveur",
    department: "salle",
    contractHours: 35,
    avatarColor: "bg-indigo-500",
  },
  {
    id: "emp-10",
    firstName: "Marie",
    lastName: "Roux",
    role: "Barmaid",
    department: "bar",
    contractHours: 28,
    avatarColor: "bg-violet-500",
  },
]

export const initialShifts: Shift[] = [
  {
    id: "shift-1",
    employeeId: "emp-1",
    day: "lundi",
    service: "midi",
    startTime: "10:00",
    endTime: "15:00",
    isFullDay: false,
  },
  {
    id: "shift-2",
    employeeId: "emp-1",
    day: "lundi",
    service: "soir",
    startTime: "18:00",
    endTime: "23:00",
    isFullDay: false,
  },
  {
    id: "shift-3",
    employeeId: "emp-2",
    day: "lundi",
    service: "midi",
    startTime: "10:00",
    endTime: "15:00",
    isFullDay: false,
  },
  {
    id: "shift-4",
    employeeId: "emp-3",
    day: "lundi",
    service: "midi",
    startTime: "09:00",
    endTime: "15:00",
    isFullDay: false,
  },
  {
    id: "shift-5",
    employeeId: "emp-3",
    day: "lundi",
    service: "soir",
    startTime: "17:00",
    endTime: "23:00",
    isFullDay: false,
  },
  {
    id: "shift-6",
    employeeId: "emp-5",
    day: "lundi",
    service: "soir",
    startTime: "18:00",
    endTime: "01:00",
    isFullDay: false,
  },
  {
    id: "shift-7",
    employeeId: "emp-2",
    day: "mardi",
    service: "midi",
    startTime: "10:00",
    endTime: "15:00",
    isFullDay: false,
  },
  {
    id: "shift-8",
    employeeId: "emp-4",
    day: "mardi",
    service: "midi",
    startTime: "09:00",
    endTime: "15:00",
    isFullDay: false,
  },
  {
    id: "shift-9",
    employeeId: "emp-4",
    day: "mardi",
    service: "soir",
    startTime: "17:00",
    endTime: "23:00",
    isFullDay: false,
  },
  {
    id: "shift-10",
    employeeId: "emp-6",
    day: "mardi",
    service: "soir",
    startTime: "18:00",
    endTime: "23:00",
    isFullDay: false,
  },
  {
    id: "shift-11",
    employeeId: "emp-7",
    day: "mercredi",
    service: "midi",
    startTime: "09:00",
    endTime: "15:00",
    isFullDay: false,
  },
  {
    id: "shift-12",
    employeeId: "emp-7",
    day: "mercredi",
    service: "soir",
    startTime: "17:00",
    endTime: "23:00",
    isFullDay: false,
  },
  {
    id: "shift-13",
    employeeId: "emp-9",
    day: "mercredi",
    service: "midi",
    startTime: "10:00",
    endTime: "15:00",
    isFullDay: false,
  },
  {
    id: "shift-14",
    employeeId: "emp-5",
    day: "mercredi",
    service: "soir",
    startTime: "18:00",
    endTime: "01:00",
    isFullDay: false,
  },
  {
    id: "shift-15",
    employeeId: "emp-1",
    day: "jeudi",
    service: "midi",
    startTime: "10:00",
    endTime: "15:00",
    isFullDay: false,
  },
  {
    id: "shift-16",
    employeeId: "emp-3",
    day: "jeudi",
    service: "midi",
    startTime: "09:00",
    endTime: "15:00",
    isFullDay: false,
  },
  {
    id: "shift-17",
    employeeId: "emp-3",
    day: "jeudi",
    service: "soir",
    startTime: "17:00",
    endTime: "23:00",
    isFullDay: false,
  },
  {
    id: "shift-18",
    employeeId: "emp-10",
    day: "jeudi",
    service: "soir",
    startTime: "18:00",
    endTime: "01:00",
    isFullDay: false,
  },
  {
    id: "shift-19",
    employeeId: "emp-2",
    day: "vendredi",
    service: "midi",
    startTime: "10:00",
    endTime: "15:00",
    isFullDay: false,
  },
  {
    id: "shift-20",
    employeeId: "emp-9",
    day: "vendredi",
    service: "midi",
    startTime: "10:00",
    endTime: "15:00",
    isFullDay: false,
  },
  {
    id: "shift-21",
    employeeId: "emp-1",
    day: "vendredi",
    service: "soir",
    startTime: "18:00",
    endTime: "23:00",
    isFullDay: false,
  },
  {
    id: "shift-22",
    employeeId: "emp-2",
    day: "vendredi",
    service: "soir",
    startTime: "18:00",
    endTime: "23:00",
    isFullDay: false,
  },
  {
    id: "shift-23",
    employeeId: "emp-5",
    day: "vendredi",
    service: "soir",
    startTime: "18:00",
    endTime: "01:00",
    isFullDay: false,
  },
  {
    id: "shift-24",
    employeeId: "emp-3",
    day: "samedi",
    service: "midi",
    startTime: "09:00",
    endTime: "15:00",
    isFullDay: false,
  },
  {
    id: "shift-25",
    employeeId: "emp-3",
    day: "samedi",
    service: "soir",
    startTime: "17:00",
    endTime: "23:00",
    isFullDay: false,
  },
  {
    id: "shift-26",
    employeeId: "emp-4",
    day: "samedi",
    service: "midi",
    startTime: "09:00",
    endTime: "15:00",
    isFullDay: false,
  },
  {
    id: "shift-27",
    employeeId: "emp-1",
    day: "samedi",
    service: "midi",
    startTime: "10:00",
    endTime: "15:00",
    isFullDay: false,
  },
  {
    id: "shift-28",
    employeeId: "emp-1",
    day: "samedi",
    service: "soir",
    startTime: "18:00",
    endTime: "23:00",
    isFullDay: false,
  },
  {
    id: "shift-29",
    employeeId: "emp-6",
    day: "samedi",
    service: "soir",
    startTime: "18:00",
    endTime: "23:00",
    isFullDay: false,
  },
  {
    id: "shift-30",
    employeeId: "emp-5",
    day: "samedi",
    service: "soir",
    startTime: "18:00",
    endTime: "01:00",
    isFullDay: false,
  },
]

export const serviceConfig: ServiceConfig = {
  midi: { start: "10:00", end: "15:00" },
  soir: { start: "18:00", end: "23:00" },
  journee: { start: "10:00", end: "23:00" },
}

export const DAILY_BUDGET = 400 // €/jour cible

export const staffingRequirements: StaffingRequirement = {
  lundi: { midi: 3, soir: 3 },
  mardi: { midi: 3, soir: 3 },
  mercredi: { midi: 3, soir: 3 },
  jeudi: { midi: 3, soir: 3 },
  vendredi: { midi: 4, soir: 4 },
  samedi: { midi: 4, soir: 5 },
  dimanche: { midi: 3, soir: 2 },
}
