# Generated by Django 5.1.7 on 2025-12-08 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="note",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "T_HOLLY_PI_NOTE",
                "verbose_name_plural": "T_HOLLY_PI_NOTE",
            },
        ),
    ]
