# Generated by Django 5.1.7 on 2025-08-18 22:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id_restaurant', models.AutoField(primary_key=True, serialize=False)),
                ('nom_restaurant', models.CharField(max_length=100)),
                ('adresse_restaurant', models.CharField(max_length=255)),
                ('code_postal', models.CharField(max_length=10)),
                ('ville', models.CharField(max_length=100)),
                ('numero_telephone', models.CharField(max_length=20)),
                ('numero_siret', models.CharField(max_length=14, unique=True, validators=[django.core.validators.RegexValidator('^\\d{14}$', 'Le SIRET doit contenir 14 chiffres.')])),
                ('code_naf', models.CharField(blank=True, max_length=5, null=True)),
            ],
            options={
                'verbose_name': 'T_HOLLY_PI_RESTAURANTS',
                'verbose_name_plural': 'T_HOLLY_PI_RESTAURANTS',
                'db_table': 'T_HOLLY_PI_RESTAURANTS',
            },
        ),
    ]
