# Generated by Django 5.1.7 on 2025-12-06 18:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="restaurant",
            name="pin_restaurant",
            field=models.CharField(
                blank=True,
                help_text="PIN à 6 chiffres pour connecter un équipement au restaurant",
                max_length=6,
                null=True,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        "^\\d{6}$",
                        "Le PIN restaurant doit contenir exactement 6 chiffres.",
                    )
                ],
            ),
        ),
    ]
