# Generated by Django 5.1.7 on 2025-12-07 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_add_logo_url_to_restaurant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='code_naf',
            field=models.CharField(blank=True, help_text="Code NAF/APE de l'établissement", max_length=10, null=True),
        ),
    ]
