# Generated by Django 5.1.7 on 2025-12-08 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant", "0004_alter_restaurant_code_naf"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="restaurant",
            options={
                "ordering": ["id_restaurant"],
                "verbose_name": "T_HOLLY_PI_RESTAURANTS",
                "verbose_name_plural": "T_HOLLY_PI_RESTAURANTS",
            },
        ),
    ]
