# Generated by Django 5.1.7 on 2025-12-12 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant", "0005_alter_restaurant_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="restaurant",
            name="latitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                help_text="Latitude géographique du restaurant",
                max_digits=9,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="restaurant",
            name="longitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                help_text="Longitude géographique du restaurant",
                max_digits=9,
                null=True,
            ),
        ),
    ]
