export const TOAST = {
  productAdded: (name: string) => `${name} ajoute a ton stock.`,
  productDeleted: (name: string) => `${name} retire du stock.`,
  orderPlaced: (supplier: string) => `Commande passee chez ${supplier}.`,
  orderDelivered: (supplier: string) => `Livraison de ${supplier} receptionnee.`,
  orderStarted: (ingredient: string) => `Commande lancee pour ${ingredient}.`,
  recipeCreated: (name: string) => `${name} ajoutee a ta carte.`,
  recipeDeleted: (name: string) => `${name} retiree de la carte.`,
  reservationConfirmed: (client: string) => `Reservation de ${client} confirmee.`,
  reservationRefused: (client: string) => `Reservation de ${client} refusee.`,
  reservationCancelled: (client: string) => `Reservation de ${client} annulee.`,
  leaveApproved: "Demande de conge approuvee.",
  allNotificationsRead: "Toutes les notifications marquees comme lues.",
  onboardingComplete: "Configuration terminee ! Bienvenue sur Holly Fork.",
  actionInDevelopment: "Action en cours de developpement.",
  permissionDenied: "Action non autorisee pour ton role.",
  serverError: "Erreur serveur — reessaie dans un instant.",
  networkError: "Connexion perdue. Verifie ton reseau.",
} as const
