import type { Establishment, Employee, Role } from "./admin-types"

const now = new Date().toISOString()

export const mockEstablishments: Establishment[] = [
  {
    id: "est-1",
    name: "Holly Fork",
    address: {
      fullAddress: "123 Rue de la Gastronomie, 75001 Paris",
      city: "Paris",
      postalCode: "75001",
      country: "France",
      longitude: 2.3522,
      latitude: 48.8566,
      mapboxId: "",
    },
    phone: "+33 1 42 36 00 00",
    email: "contact@hollyfork.fr",
    siret: "12345678901234",
    tvaNumber: "FR12345678901",
    legalForm: "sas",
    totalCapacity: 48,
    openingDays: ["lundi", "mardi", "mercredi", "jeudi", "vendredi", "samedi"],
    services: [
      { id: "svc-1", name: "Midi", startTime: "10:00", endTime: "15:00" },
      { id: "svc-2", name: "Soir", startTime: "18:00", endTime: "23:00" },
    ],
    storageZones: [
      { id: "zone-1", name: "Chambre froide A", slug: "chambre_froide_a", type: "cold", targetTemperature: 3 },
      { id: "zone-2", name: "Chambre froide B", slug: "chambre_froide_b", type: "cold", targetTemperature: -18 },
      { id: "zone-3", name: "Réserve légumes", slug: "reserve_legumes", type: "cold", targetTemperature: 8 },
      { id: "zone-4", name: "Réserve sèche", slug: "reserve_seche", type: "dry" },
      { id: "zone-5", name: "Cave", slug: "cave", type: "cellar", targetTemperature: 14 },
    ],
    isActive: true,
    legalInfo: {
      licenseType: "licence_iv",
      licenseNumber: "75-2024-00123",
      insurance: "AXA Pro Restauration",
      erpCapacity: 60,
      notes: "",
    },
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "est-2",
    name: "Le Petit Bistrot",
    address: {
      fullAddress: "45 Avenue des Champs-Élysées, 75008 Paris",
      city: "Paris",
      postalCode: "75008",
      country: "France",
      longitude: 2.3075,
      latitude: 48.8698,
      mapboxId: "",
    },
    phone: "+33 1 43 59 00 00",
    email: "contact@lepetitbistrot.fr",
    siret: "98765432109876",
    tvaNumber: "FR98765432109",
    legalForm: "sarl",
    totalCapacity: 32,
    openingDays: ["mardi", "mercredi", "jeudi", "vendredi", "samedi"],
    services: [
      { id: "svc-4", name: "Midi", startTime: "12:00", endTime: "14:30" },
      { id: "svc-5", name: "Soir", startTime: "19:00", endTime: "22:30" },
    ],
    storageZones: [
      { id: "zone-6", name: "Chambre froide", slug: "chambre_froide", type: "cold", targetTemperature: 3 },
      { id: "zone-7", name: "Réserve sèche", slug: "reserve_seche", type: "dry" },
    ],
    isActive: false,
    legalInfo: {
      licenseType: "licence_iii",
      licenseNumber: "75-2023-00456",
      insurance: "Allianz Restauration",
      erpCapacity: 40,
      notes: "",
    },
    createdAt: now,
    updatedAt: now,
  },
]

export const mockEmployees: Employee[] = [
  {
    id: "emp-1",
    firstName: "Lucas",
    lastName: "Martin",
    email: "lucas.martin@hollyfork.fr",
    phone: "+33 6 12 34 56 78",
    dateOfBirth: "1995-03-15",
    address: "12 Rue de Rivoli, 75001 Paris",
    position: "chef_de_rang",
    department: "salle",
    establishmentId: "est-1",
    contractType: "cdi",
    hireDate: "2022-09-01",
    weeklyHours: 35,
    hourlyRate: 13.5,
    roleId: "role-3",
    loginEmail: "lucas.martin@hollyfork.fr",
    accountStatus: "active",
    avatarColor: "bg-blue-500",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "emp-2",
    firstName: "Emma",
    lastName: "Dubois",
    email: "emma.dubois@hollyfork.fr",
    phone: "+33 6 23 45 67 89",
    dateOfBirth: "1998-07-22",
    address: "8 Boulevard Saint-Germain, 75005 Paris",
    position: "serveur",
    department: "salle",
    establishmentId: "est-1",
    contractType: "cdi",
    hireDate: "2023-01-15",
    weeklyHours: 35,
    hourlyRate: 12.0,
    roleId: "role-4",
    loginEmail: "emma.dubois@hollyfork.fr",
    accountStatus: "active",
    avatarColor: "bg-pink-500",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "emp-3",
    firstName: "Hugo",
    lastName: "Bernard",
    email: "hugo.bernard@hollyfork.fr",
    phone: "+33 6 34 56 78 90",
    dateOfBirth: "1988-11-05",
    address: "25 Rue du Faubourg Saint-Antoine, 75011 Paris",
    position: "chef_cuisinier",
    department: "cuisine",
    establishmentId: "est-1",
    contractType: "cdi",
    hireDate: "2020-06-01",
    weeklyHours: 39,
    hourlyRate: 18.0,
    roleId: "role-2",
    loginEmail: "hugo.bernard@hollyfork.fr",
    accountStatus: "active",
    avatarColor: "bg-orange-500",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "emp-4",
    firstName: "Chloé",
    lastName: "Petit",
    email: "chloe.petit@hollyfork.fr",
    phone: "+33 6 45 67 89 01",
    dateOfBirth: "1999-02-18",
    address: "3 Rue de la Paix, 75002 Paris",
    position: "commis",
    department: "cuisine",
    establishmentId: "est-1",
    contractType: "cdi",
    hireDate: "2023-03-01",
    weeklyHours: 35,
    hourlyRate: 11.65,
    roleId: "role-4",
    loginEmail: "chloe.petit@hollyfork.fr",
    accountStatus: "active",
    avatarColor: "bg-emerald-500",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "emp-5",
    firstName: "Nathan",
    lastName: "Leroy",
    email: "nathan.leroy@hollyfork.fr",
    phone: "+33 6 56 78 90 12",
    dateOfBirth: "1993-09-30",
    address: "17 Rue Oberkampf, 75011 Paris",
    position: "barman",
    department: "bar",
    establishmentId: "est-1",
    contractType: "cdi",
    hireDate: "2021-11-15",
    weeklyHours: 35,
    hourlyRate: 13.0,
    roleId: "role-4",
    loginEmail: "nathan.leroy@hollyfork.fr",
    accountStatus: "active",
    avatarColor: "bg-purple-500",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "emp-6",
    firstName: "Léa",
    lastName: "Moreau",
    email: "lea.moreau@hollyfork.fr",
    phone: "+33 6 67 89 01 23",
    dateOfBirth: "2001-05-12",
    address: "42 Rue de la Roquette, 75011 Paris",
    position: "serveur",
    department: "salle",
    establishmentId: "est-1",
    contractType: "cdd",
    hireDate: "2025-06-01",
    endDate: "2026-06-30",
    weeklyHours: 24,
    hourlyRate: 11.65,
    roleId: "role-4",
    loginEmail: "lea.moreau@hollyfork.fr",
    accountStatus: "active",
    avatarColor: "bg-rose-500",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "emp-7",
    firstName: "Thomas",
    lastName: "Simon",
    email: "thomas.simon@hollyfork.fr",
    phone: "+33 6 78 90 12 34",
    dateOfBirth: "1990-12-08",
    address: "9 Rue des Martyrs, 75009 Paris",
    position: "second_de_cuisine",
    department: "cuisine",
    establishmentId: "est-1",
    contractType: "cdi",
    hireDate: "2021-02-01",
    weeklyHours: 39,
    hourlyRate: 15.0,
    roleId: "role-2",
    loginEmail: "thomas.simon@hollyfork.fr",
    accountStatus: "active",
    avatarColor: "bg-amber-500",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "emp-8",
    firstName: "Julie",
    lastName: "Laurent",
    email: "julie.laurent@hollyfork.fr",
    phone: "+33 6 89 01 23 45",
    dateOfBirth: "1997-08-25",
    address: "6 Rue de Belleville, 75020 Paris",
    position: "plongeur",
    department: "plonge",
    establishmentId: "est-1",
    contractType: "cdi",
    hireDate: "2023-09-01",
    weeklyHours: 35,
    hourlyRate: 11.65,
    roleId: "role-4",
    loginEmail: "julie.laurent@hollyfork.fr",
    accountStatus: "active",
    avatarColor: "bg-teal-500",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "emp-9",
    firstName: "Antoine",
    lastName: "Garcia",
    email: "antoine.garcia@hollyfork.fr",
    phone: "+33 6 90 12 34 56",
    dateOfBirth: "1996-04-03",
    address: "15 Rue de Charonne, 75011 Paris",
    position: "serveur",
    department: "salle",
    establishmentId: "est-1",
    contractType: "cdi",
    hireDate: "2022-05-01",
    weeklyHours: 35,
    hourlyRate: 12.0,
    roleId: "role-4",
    loginEmail: "antoine.garcia@hollyfork.fr",
    accountStatus: "active",
    avatarColor: "bg-indigo-500",
    createdAt: now,
    updatedAt: now,
  },
  {
    id: "emp-10",
    firstName: "Marie",
    lastName: "Roux",
    email: "marie.roux@hollyfork.fr",
    phone: "+33 6 01 23 45 67",
    dateOfBirth: "1994-01-20",
    address: "28 Rue du Temple, 75003 Paris",
    position: "barman",
    department: "bar",
    establishmentId: "est-1",
    contractType: "cdd",
    hireDate: "2025-09-01",
    endDate: "2026-08-31",
    weeklyHours: 28,
    hourlyRate: 12.5,
    roleId: "role-4",
    loginEmail: "marie.roux@hollyfork.fr",
    accountStatus: "active",
    avatarColor: "bg-violet-500",
    createdAt: now,
    updatedAt: now,
  },
]

export const mockRoles: Role[] = [
  {
    id: "role-1",
    name: "gerant",
    label: "Gérant",
    description: "Accès complet à toutes les fonctionnalités de l'application.",
    permissions: {
      dashboard: { read: true, write: true },
      reservations: { read: true, write: true },
      salle: { read: true, write: true },
      planning: { read: true, write: true },
      cuisine: { read: true, write: true },
      stocks: { read: true, write: true },
      fournisseurs: { read: true, write: true },
      admin: { read: true, write: true },
    },
  },
  {
    id: "role-2",
    name: "chef",
    label: "Chef",
    description: "Gestion de la cuisine, des stocks et consultation du planning.",
    permissions: {
      dashboard: { read: true, write: false },
      reservations: { read: false, write: false },
      salle: { read: false, write: false },
      planning: { read: true, write: false },
      cuisine: { read: true, write: true },
      stocks: { read: true, write: true },
      fournisseurs: { read: false, write: false },
      admin: { read: false, write: false },
    },
  },
  {
    id: "role-3",
    name: "responsable_salle",
    label: "Responsable salle",
    description: "Gestion des réservations, de la salle et consultation du planning.",
    permissions: {
      dashboard: { read: true, write: false },
      reservations: { read: true, write: true },
      salle: { read: true, write: true },
      planning: { read: true, write: false },
      cuisine: { read: false, write: false },
      stocks: { read: false, write: false },
      fournisseurs: { read: false, write: false },
      admin: { read: false, write: false },
    },
  },
  {
    id: "role-4",
    name: "serveur",
    label: "Serveur",
    description: "Consultation des réservations et de la salle.",
    permissions: {
      dashboard: { read: false, write: false },
      reservations: { read: true, write: false },
      salle: { read: true, write: false },
      planning: { read: false, write: false },
      cuisine: { read: false, write: false },
      stocks: { read: false, write: false },
      fournisseurs: { read: false, write: false },
      admin: { read: false, write: false },
    },
  },
]
