# Generated by Django 5.1.7 on 2025-12-12 10:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("restaurant", "0005_alter_restaurant_options"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Report",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "type_report",
                    models.CharField(
                        choices=[
                            ("SALES", "Ventes"),
                            ("STOCK", "Stocks"),
                            ("STAFF", "Personnel"),
                            ("FINANCIAL", "Financier"),
                            ("CUSTOM", "Personnalisé"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("periode_debut", models.DateField(db_index=True)),
                ("periode_fin", models.DateField(db_index=True)),
                (
                    "fichier",
                    models.FileField(blank=True, null=True, upload_to="reports/"),
                ),
                (
                    "generated_at",
                    models.DateTimeField(auto_now_add=True, db_index=True),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "restaurant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="restaurant.restaurant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Rapport",
                "verbose_name_plural": "Rapports",
                "db_table": "T_HOLLY_PI_REPORTS",
                "ordering": ["-generated_at"],
                "indexes": [
                    models.Index(
                        fields=["restaurant", "type_report", "generated_at"],
                        name="T_HOLLY_PI__restaur_bc811f_idx",
                    )
                ],
            },
        ),
    ]
