# Generated by Django 5.1.7 on 2025-08-18 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TauxTVA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('taux', models.DecimalField(db_index=True, decimal_places=2, help_text='Taux de TVA en pourcentage', max_digits=4)),
                ('description', models.CharField(db_index=True, help_text='Description du taux (ex: Taux normal, Taux réduit)', max_length=255)),
                ('actif', models.BooleanField(db_index=True, default=True)),
            ],
            options={
                'verbose_name': 'T_HOLLY_PI_TAUX_TVA',
                'verbose_name_plural': 'T_HOLLY_PI_TAUX_TVA',
                'db_table': 'T_HOLLY_PI_TAUX_TVA',
                'indexes': [models.Index(fields=['taux', 'actif'], name='T_HOLLY_PI__taux_0145f8_idx')],
            },
        ),
    ]
