# Generated by Django 5.1.7 on 2025-12-12 10:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("restaurant", "0005_alter_restaurant_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="BillingSettings",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "tva_par_defaut",
                    models.DecimalField(decimal_places=2, default=20.0, max_digits=5),
                ),
                ("devise", models.CharField(default="EUR", max_length=3)),
                ("facture_auto", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "restaurant",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="billing_settings",
                        to="restaurant.restaurant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Paramètres de facturation",
                "verbose_name_plural": "Paramètres de facturation",
                "db_table": "T_HOLLY_PI_BILLING_SETTINGS",
            },
        ),
        migrations.CreateModel(
            name="NotificationSettings",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("email_notifications", models.BooleanField(default=True)),
                ("sms_notifications", models.BooleanField(default=False)),
                ("stock_alerts", models.BooleanField(default=True)),
                ("reservation_alerts", models.BooleanField(default=True)),
                ("command_alerts", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "restaurant",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notification_settings",
                        to="restaurant.restaurant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Paramètres de notifications",
                "verbose_name_plural": "Paramètres de notifications",
                "db_table": "T_HOLLY_PI_NOTIFICATION_SETTINGS",
            },
        ),
    ]
