# Generated by Django 5.1.7 on 2025-12-12 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("settings", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="billingsettings",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Paramètres de facturation",
                "verbose_name_plural": "Paramètres de facturation",
            },
        ),
        migrations.AlterModelOptions(
            name="notificationsettings",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Paramètres de notifications",
                "verbose_name_plural": "Paramètres de notifications",
            },
        ),
    ]
