# Generated by Django 5.1.7 on 2025-12-12 10:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("restaurant", "0005_alter_restaurant_options"),
        ("staff", "0005_alter_employe_options_alter_typeemploye_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="Shift",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("date_debut", models.DateTimeField(db_index=True)),
                ("date_fin", models.DateTimeField(db_index=True)),
                (
                    "type_shift",
                    models.CharField(
                        choices=[
                            ("MORNING", "Matin"),
                            ("AFTERNOON", "Après-midi"),
                            ("EVENING", "Soir"),
                            ("NIGHT", "Nuit"),
                        ],
                        default="MORNING",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "employe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shifts",
                        to="staff.employe",
                    ),
                ),
                (
                    "restaurant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="restaurant.restaurant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Créneau horaire",
                "verbose_name_plural": "Créneaux horaires",
                "db_table": "T_HOLLY_PI_SHIFTS",
                "ordering": ["date_debut"],
                "indexes": [
                    models.Index(
                        fields=["restaurant", "date_debut"],
                        name="T_HOLLY_PI__restaur_d0b1c3_idx",
                    ),
                    models.Index(
                        fields=["employe", "date_debut"],
                        name="T_HOLLY_PI__employe_718b28_idx",
                    ),
                    models.Index(
                        fields=["date_debut", "date_fin"],
                        name="T_HOLLY_PI__date_de_06717b_idx",
                    ),
                ],
            },
        ),
    ]
